from typing import Literal

role_list = Literal[
    "CEO (Chief Executive Officer)",
    "CTO (Chief Technology Officer)",
    "CIO (Chief Information Officer)",
    "Head of Development",
    "Head of Product",
    "Product Owner",
    "Product Manager",
    "Project Manager",
    "Program Manager",
    "Scrum Master",
    "Business Analyst",
    "Systems Analyst",
    "Product Analyst",
    "Data Analyst",
    "BI Analyst",
    "Software Architect",
    "Solution Architect",
    "Data Architect",
    "Tech Lead",
    "Team Lead",
    "Engineering Manager",
    "Backend Developer",
    "Frontend Developer",
    "Full Stack Developer",
    "Java Developer",
    "Python Developer",
    "C# / .NET Developer",
    "Go Developer",
    "PHP Developer",
    "Node.js Developer",
    "iOS Developer",
    "Android Developer",
    "React Developer",
    "Vue.js Developer",
    "Data Scientist",
    "Data Engineer",
    "ML Engineer",
    "QA Engineer (Manual)",
    "QA Automation Engineer",
    "DevOps Engineer",
    "System Administrator",
    "SRE (Site Reliability Engineer)",
    "Security Engineer",
    "Cloud Engineer",
    "UX/UI Designer",
    "Product Designer",
    "UX Researcher",
    "Technical Writer",
    "SEO Specialist",
    "Delivery Manager",
    "Customer Success Manager",
    "Tech Support Engineer",
    "IT Specialist"
]